### ISSUE TITLE
测试用例一直执行中

### ISSUE THREAD

**Issue by zhangwenkal** [t880216t/manager-server#1]
127.0.0.1 - - [13/Jun/2018 19:53:11] "POST /build HTTP/1.1" 200 -
Traceback (most recent call last):
  File "makeTestCase.py", line 6, in <module>
    from app.static.interface_auto.common import common
  File "E:\F\git_zhangwenkal\manager-server-master\app\__init__.py", line 1, in <module>
    from flask import Flask
ImportError: No module named 'flask'
127.0.0.1 - - [13/Jun/2018 19:53:13] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:15] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:17] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:19] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:21] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:23] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:25] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:27] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:29] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:31] "POST /interfaceTaskList HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2018 19:53:33] "POST /interfaceTaskList HTTP/1.1" 200 -
![image](https://user-images.githubusercontent.com/19470764/41350291-3cb9037c-6f45-11e8-910e-1204bc66cfee.png)

**Comment by t880216t** [comment]
是先走置任务状态的接口后，在生成文件时报错了。后面的没走，问题在于没有找到flask模块，这是情况一般是python环境不对。你有用python 虚拟环境吗，可以试下再安装下flask模块。
